### ISSUE TITLE
Vox not able to transform

### ISSUE THREAD

**Issue by SilverWolf147** [SattesKrokodil/Fabric-Adventure-Pack#11]
**Describe the bug**
When using the vox origin, attempting to transform either into the fox or fish does nothing

**To Reproduce**
1. Choose Vox origin
2. Either click Jump + G, or immerse yourself in water and press g
3. Nothing happens

**Expected behavior**
I would expect for either the character model to change or for some buff to be applied but neither happens

**Desktop (please complete the following information):**
 - Launcher MultiMC
 - Version AP - 4.3.1
 - OS Windows 10

**Comment by SattesKrokodil** [comment]
sounds like you are missing some datapacks? did you try it in singleplayer or do you play on a server? only issue with vox is that it cant transform in caves, which will be fixed soon

**Comment by MrRubberDucky** [comment]
> sounds like you are missing some datapacks? did you try it in singleplayer or do you play on a server? only issue with vox is that it cant transform in caves, which will be fixed soon

Vox sometimes also doesn't transfer in water ex. underground caves from what I've noticed.

**Comment by SilverWolf147** [comment]
I am playing on a server my brother set up, so I did try to load up a single player world and you are correct the transformation does work there, so I guess there is a data pack missing from the server.  Any idea which one though?

**Comment by SattesKrokodil** [comment]
what origins version do you use on the server/client?

**Comment by SilverWolf147** [comment]
Looks like Origins 0.5.1 and Origin Classes 1.1.1

**Comment by SilverWolf147** [comment]
Turns out there were some issues server side and the mod Identity accidentally got deleted.
