### ISSUE TITLE
Add Two players one horse

### ISSUE THREAD

**Issue by Borregon** [SattesKrokodil/Fabric-Adventure-Pack#14]
https://www.curseforge.com/minecraft/mc-mods/two-players-one-horse

FABRIC version: https://www.curseforge.com/minecraft/mc-mods/dual-riders

**Comment by SattesKrokodil** [comment]
we had that one in for a while but nobody really used it/!knew about it, I doubt that it offers value right now because of the elytra/wings meta. It is a really nice mod and personally I prefer horses/mounts but in the end it is just "bloat" due to flight mechanix x(
