### ISSUE TITLE
Make it more playable for new players

### ISSUE THREAD

**Issue by lazyfred98** [SattesKrokodil/Fabric-Adventure-Pack#19]
Today I started playing on the official server and after ~2.5h I just gave up. There are no towers left for low level players and it's frustrating af if you play for hours to get less stuff than you would get from a single tower.

The first solution I have in mind for this problem is a second world which get resettet regularly so there are always towers for new players left.

My alternate solution is one I'm not sure if it is possible. I know you can regenerate existing chunks. Maybe it's possible to regenerate all unclaimed chunks every so often. Or maybe if it's possible just regenerate the towers.

I really like the modpack and I hope there will be a solution for this Problem.

Thanks for reading the post and have a nice day

**Comment by SattesKrokodil** [comment]
the modpack relaunch should fix this issue. also the official server has different settings now (lvl 1-10) and a big enough pregeneration. Nether, End, Hell reset every once in a while and Spawn HUB in another dimension makes it easy to move spawn if needed. Thank you for the feedback, sorry it took so long to answer

**Comment by SattesKrokodil** [comment]
the modpack relaunch should fix this issue. also the official server has different settings now (lvl 1-10) and a big enough pregeneration. Nether, End, Hell reset every once in a while and Spawn HUB in another dimension makes it easy to move spawn if needed. Thank you for the feedback, sorry it took so long to answer
