### ISSUE TITLE
Could not find required mod

### ISSUE THREAD

**Issue by Wazard** [SattesKrokodil/Fabric-Adventure-Pack#2]
Could not find required mod: xpstorage requires {minecraft @ [1.16.3]}
Creating Empty clause ?

**Comment by chronosacaria** [comment]
Hi Wazard! Are you using 1.16.3 or 1.16.4?

**Comment by Wazard** [comment]
My bad, my bad. I was using fabric 1.16.4 'cause the curseforge page said it was for Minecraft 1.16.4 . Switching to 1.16.3 0.18 solved the issue

**Comment by chronosacaria** [comment]
Awesome! Thanks for mentioning that the version is off on the CurseForge page!
