### ISSUE TITLE
GUI scale is artificially restricted

### ISSUE THREAD

**Issue by Seegras** [SattesKrokodil/Fabric-Adventure-Pack#20]
Due to the different GUI, the option "GUI scale" is limited to 0-4. On Vanilla, it's 0-8. Please adjust, as on 4k displays, 0 (auto) is too big, and 4 is somewhat too small.

**Comment by gaycookie** [comment]
This is done using Sodium, if you want the original "vanilla" settings for your visual back, you'll have to disable Sodium mod.
I do not know if you can hardcode the settings via a config file, but if you only wanna do it via the UI, you stuck with 0-4 on Sodium

**Comment by Seegras** [comment]
Thanks; I'll report this to sodium then.
