### ISSUE TITLE
Game Crushed and i can't join the wolrd anymore

### ISSUE THREAD

**Issue by BlazeAmaroq** [SattesKrokodil/Fabric-Adventure-Pack#22]
**Describe the bug**
After 114 days in game or so, the game crushed and i can't join the world any more. At first i thought it was my DynoCapsule error, so i tried to start the world without that mod, but it didn't work.

Here is a link for the Crush report. can you give it a look please?
https://pastebin.com/QnxTtrkc

**Comment by SattesKrokodil** [comment]
what modpack version do you play with?

**Comment by BlazeAmaroq** [comment]
4.3.3

**Comment by grizllym** [comment]
I have destroyed 2 worlds now... Flying in creative around for about 10 min crashed world and i cant load it anymore crashing immediately after load. 4.3.3 version. Attaching the crash report. 
[crash-2021-04-12_17.03.23-server.txt](https://github.com/SattesKrokodil/Fabric-Adventure-Pack/files/6297935/crash-2021-04-12_17.03.23-server.txt)

**Comment by SattesKrokodil** [comment]
didn't happen again, no idea what it was - not relevant for 4.4.0+ since we yeeted a lot of mods and no crashes like that so far and no issues in pregenerating 40k worldborder
