### ISSUE TITLE
Game crushing when drop AoE item in open LAN MP

### ISSUE THREAD

**Issue by grizllym** [SattesKrokodil/Fabric-Adventure-Pack#24]
**Describe the bug**
When some player drop AoE item on ground in open LAN multiplayer game crashes.

**To Reproduce**
1. Drop AoE item.

**Expected behavior**
Not crash.

**Desktop (please complete the following information):**
 - Launcher - CurseForge
 - Version - 4.3.3
 - OS - Windows 10

[crash-2021-04-14_20.47.34-server.txt](https://github.com/SattesKrokodil/Fabric-Adventure-Pack/files/6313063/crash-2021-04-14_20.47.34-server.txt)

**Comment by gaycookie** [comment]
As far as I know and also as far as I can read from the crash log.
The mod: `LootBeams` is the cause of this, I've had this issue myself too and I stopped using that mod.
_The mod is I think a client-side only mod, so you should be fine removing it._ (Not 100% sure)

**Comment by grizllym** [comment]
Seems like that fixed it. Thanks 👍
