### ISSUE TITLE
Crash When Dropping Enchanted Book

### ISSUE THREAD

**Issue by Alonsinwhat** [SattesKrokodil/Fabric-Adventure-Pack#27]
**Describe the bug**
When you drop an enchanted book with q or from inventory, the game crashes and minecraft closes. This happened to me 100% of the times on a LAN server located on my computer

**To Reproduce**
1. Press "Q" with Enchanted Book on hand
2. Game Crashes.
or
1. Directly drop enchanted book from inventory
2. Game Crashes.

**Expected behavior**
The game should just drop the book without problem-

**Screenshots**
The game would crash and i wouldnt be able to take a screenshot so...

**Desktop (please complete the following information):**
 - Launcher: CurseForge
 - Version [e.g. AP - 4.3.0]
 - Windows 10 20H2 (19042.985)
 
**Additional context**
This happened when i tried to throw a book to my friend on one of these tower dungeons.

**Comment by Alonsinwhat** [comment]
i forgot to add the version, it is 4.3.3

**Comment by P03W** [comment]
Known issue, update lootbeams

**Comment by SattesKrokodil** [comment]
fixed in version 4.4.0 and higher (update lootbeams to 2.0.2 if you don't want to play a higher version)
