### ISSUE TITLE
Chunks fusing together (Visual Glitch)

### ISSUE THREAD

**Issue by Ventago** [SattesKrokodil/Fabric-Adventure-Pack#32]
When ever I load up a world  after a minute or two every block from every chunk that is loaded is merged with my chunk that I'm currently in. this is a visual glitch, the blocks themselves aren't actually converging the just basically don't allow you to see

1. Open a new singleplayer world
2. wait 1 or 2 minutes

**Expected behavior**
![20210720_093130](https://user-images.githubusercontent.com/50640179/126335410-1a5b8607-9ebb-4a7d-9153-d2751dfe2498.jpg)
![20210720_093225](https://user-images.githubusercontent.com/50640179/126335418-acbb81d2-5751-4cdf-8f8a-bba8e8f73d55.jpg)

**Desktop (please complete the following information):**
Multimc
Version 4.5.2
Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz   3.20 GHz
8GB ram for the modpack

**Comment by Panderine** [comment]
What GPU are you using? This seems a sodium mod bug

**Comment by SattesKrokodil** [comment]
I've never seen this before and have no idea on how to help/approach it.. Others don't seem to experience it. I'll reopen this if it occurs again
