### ISSUE TITLE
server reset on Sept. 5, 2021 at 9:50ish EST caused my shurker box to disappear

### ISSUE THREAD

**Issue by Blevon** [SattesKrokodil/Fabric-Adventure-Pack#37]
my daughter (KaitlynJedi) and I (Blevon6234) were exploring the area is preparation to take a boat to one of out bases. I dropped an uncommon shurker bow, which is where I store my stuff so it will not get lost. I had just pulled out a boat and was hitting the shurker box with my axe when the server when down for a couple minutes., when we were able to log back in, the shurker bow was missing. It was not in either of our inventory, nor was it still on the ground.  It has 6 common shurker boxes in it with 3.5 of them full, about 11 boss keys, 3 common keys, a dungeon key, 2 oak boats, 4 condensed essenses.  The common shurker boxes held the loot from a dungeon tower we had just cleared earlier.  How can I get the box back? Location is 389, 63, -535

**Comment by Blevon** [comment]
Location is 389, 63, -535

**Comment by SattesKrokodil** [comment]
should be solved, better place for this is the discord (=

have a nice day you two!
