### ISSUE TITLE
Appearance of lower health when joining server

### ISSUE THREAD

**Issue by kyleblane** [SattesKrokodil/Fabric-Adventure-Pack#4]
When we join our server our health appears to be low, but it's actually full. Only once we take damage does it correct itself. Not a huge deal, but Chronos asked me to add it here. Thanks! Happy hunting!

Clip of issue.
https://clips.twitch.tv/VenomousUgliestChimpanzeeCorgiDerp

**Comment by SattesKrokodil** [comment]
this is sadly a visual bug caused by Age of Exile - we can't really do much about it )=
