### ISSUE TITLE
How do I use Waystones? [QUESTION]

### ISSUE THREAD

**Issue by DeadlyAccurate** [SattesKrokodil/Fabric-Adventure-Pack#44]
Modpack 4.5.2

I can't figure out how to use Waystones. When I click on them, I don't teleport, even between two of them I found and claimed.

**Comment by panbanann** [comment]
When you open the waystone interface you have the teleportation cost which are the essences. You need to have enough to be able to teleport. 
Don't create issues on GitHub if you have more questions, please join Adventure Pack discord and ask them there - faster answers for you less non-issue issues on github.

**Comment by DeadlyAccurate** [comment]
I actually tried Discord first. I looked all over trying to find a place to ask questions, but all I see are info channels. I clicked on every channel several times trying to figure out where everyone is asking questions and talking, and I just can't see it. I can post a picture of my channel list if you'd like to see it.

**Comment by popsapeter** [comment]
Go to rules, and read it THOROUGHLY, after which go to role-select, and read that as well. You will have all the info afterwards.

**Comment by DeadlyAccurate** [comment]
Thank you. I didn't see anything called role-select, so I'm not sure how to do this, but I have my answer on the waystone, so I appreciate the help.
