### ISSUE TITLE
Waila crashes the client when trying to open the configuration

### ISSUE THREAD

**Issue by adkinss** [SattesKrokodil/Fabric-Adventure-Pack#5]
When trying to configure Waila, it crashes the client.

Bring up the Waila configuration menu by doing either of the following:
* From the Mod Menu, click on Hwyla and click on the settings icon.
* From in-game, press the 0 key on numeric keypad.

To reproduce the crash, click on either the "Waila Settings" button or the the "Plugin Settings" button.  The crash happens whether you are in game or not, in both single and multiplayer games, and is reproduceable in both 4.0.6 (client & server) and 4.0.9 (client).

**Comment by adkinss** [comment]
Crash Report: https://pastebin.com/Br3WdAQU

Also, you may notice that I added "rad: Reload Audio driver 1.0.1" to the mod list.  This allows me to reload audio drivers instantly without having to do the full reload resources route.  However, I only just added it, the crashes were occuring before I added the mod.  No other changes to the default configuration or mod list was done.

**Comment by chronosacaria** [comment]
This is a known issue with Hwyla and is not related to Adventure Pack, though we do make use of Hwyla in the pack. From what I understand TehNut is aware of the issue but they are taking a break at this time. There is no way for us to be able to fix this issue as it is related to Hwyla, not us.
