### ISSUE TITLE
Lootbeams sometimes do not disappear after picking up items

### ISSUE THREAD

**Issue by MrRubberDucky** [SattesKrokodil/Fabric-Adventure-Pack#9]
**Describe the bug**
Loot beams do not disappear and instead remain on users' screen after the user picks up items from his death.

**To Reproduce**
1. probably die somewhere
2. try picking up items again

**Expected behavior**
Loot beam disappears after picking up a item

**Screenshots**
[Screenshot 1](https://cdn.discordapp.com/attachments/635489949046538270/814504553252519946/2021-02-25_15.05.40.png)
[Screenshot 2](https://cdn.discordapp.com/attachments/635489949046538270/814505081671647332/2021-02-25_15.15.17.png)

**Desktop (please complete the following information):**
 - Launcher: MultiMC
 - Version: AP 4.3.1
 - OS: Win10 1909

**Comment by P03W** [comment]
Known lootbeams problem, will be fixed in next iteration of lootbeams
